# Git aliases
alias g 'git'
alias ga 'git add'
alias gaa 'git add --all'
alias gc 'git commit'
alias gcm 'git commit -m'
alias gco 'git checkout'
alias gs 'git status'
alias gl 'git log'
alias glo 'git log --oneline'
alias gp 'git push'
alias gpl 'git pull'
alias gb 'git branch'
alias gd 'git diff'
alias gdc 'git diff --cached'
alias gr 'git reset'
alias grh 'git reset --hard'
alias gf 'git fetch'
alias gm 'git merge'
alias grs 'git restore'
alias gst 'git stash'
alias gstp 'git stash pop'
alias gstl 'git stash list'
alias gwt 'git worktree'